export interface Children {
  alignment: number
  'disc-aln': number
  dax: boolean
  'disc-gran': number
  'disc-max': number
  'disc-zero': boolean
  fsavail?: number
  fsroots: string | undefined[]
  fssize?: number
  fstype: string
  fsused?: number
  'fsuse%'?: string
  fsver?: string
  group: string
  hctl: any
  hotplug: boolean
  kname: string
  label?: string
  'log-sec': number
  'maj:min': string
  'min-io': number
  mode: string
  model: any
  name: string
  'opt-io': number
  owner: string
  partflags?: string
  partlabel: any
  parttype: string
  parttypename: string
  partuuid?: string
  path: string
  'phy-sec': number
  pkname: string
  pttype: string
  ptuuid?: string
  ra: number
  rand: boolean
  rev: any
  rm: boolean
  ro: boolean
  rota: boolean
  'rq-size': number
  sched: string
  serial: any
  size: number
  start: number
  state: any
  subsystems: string
  mountpoint?: string
  mountpoints: string | undefined[]
  tran?: string
  type: string
  uuid: string
  vendor: any
  wsame: number
  wwn?: string
  zoned: string
  'zone-sz': number
  'zone-wgran': number
  'zone-app': number
  'zone-nr': number
  'zone-omax': number
  'zone-amax': number
}
